version: 2
jobs:
  build:
    machine: true
    image: circleci/classic:latest
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
    - run: yarn install
    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
    # Rubocop
    - run:
        name: Rubocop
        command: bundle exec rubocop
