version: 2

jobs:
  hello_world_job:
    docker:
      - image: circleci/ruby

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: execute hello world
          command: |
            echo 'hello world'